name: publish to sonatype ossrh

on:
  push:
    branch:
      - feature/github-release

jobs:
  publish-artifacts:
    name: build and publish artifacts
    runs-on: ubuntu-18.04
    env:
      REF: ${{ github.ref }}

    steps:
      - name: Checkout Project
        uses: actions/checkout@v1

      -
        name: Setup Java
        uses: actions/setup-java@v1.3.0
        with:
          java-version: '8'

      -
        name: Cache Gradle
        id: gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('ktcheck-api/build.gradle.kts') }}-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: gradle-

      -
        name: Show Task
        run: |
          ORG_GRADLE_PROJECT_KT_CHECK_VERSION=v0.1.0 \
            ./gradlew tasks --all
        env:
          ORG_GRADLE_PROJECT_privateKey: ${{ secrets.PGP_ARMORED_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_pgpPassword: ${{ secrets.PGP_PASS_PHREASE }}
          ORG_GRADLE_PROJECT_githubPackageUrl: "https://maven.pkg.github.com/mike_neck/ktcheck"
          ORG_GRADLE_PROJECT_githubUsername: ${{ github.event.repository.owner.login }}
          ORG_GRADLE_PROJECT_githubToken: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Dry run github release
        run: |
          ORG_GRADLE_PROJECT_KT_CHECK_VERSION=v0.1.0 \
            ./gradlew publishGithubAll --dry-run
        env:
          ORG_GRADLE_PROJECT_privateKey: ${{ secrets.PGP_ARMORED_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_pgpPassword: ${{ secrets.PGP_PASS_PHREASE }}
          ORG_GRADLE_PROJECT_githubPackageUrl: "https://maven.pkg.github.com/mike_neck/ktcheck"
          ORG_GRADLE_PROJECT_githubUsername: ${{ github.event.repository.owner.login }}
          ORG_GRADLE_PROJECT_githubToken: ${{ secrets.GITHUB_TOKEN }}
